### ISSUE TITLE
Passing input in the URL to get last 2 hours data

### ISSUE THREAD

**Issue by manjunathnayaka22** [yesoreyeram/grafana-infinity-panel#10]
I am passing this url in Infinity plugin to get the data for specific interval manually. Do we have any option to get the data from last 30 min to current time without modifying every time.

https://test.com/me/r/calls/2022-05-25+11:30:00/2022-05-25+11:58:00

**Comment by yesoreyeram** [comment]
refer https://github.com/yesoreyeram/grafana-infinity-datasource/discussions

**Comment by manjunathnayaka22** [comment]
Thank you @yesoreyeram for your quick response on this. Unfortunately I dint get a solution from above said link.
Basically when I execute below link directly through Infinity plugin it get the data from test.com page and in the data setup_start_ts column shows the date and time. So without entering start and time in the url how to add input through variable for this column, so that I can choose last 10 or 15 min data by choosing input. 

Sample URL:
Example with date and time : https://test.com/me/r/calls/2022-05-25+11:30:00/2022-05-25+11:58:00

**Comment by yesoreyeram** [comment]
I would say the solution definitely in the above link and also refer https://grafana.com/docs/grafana/latest/variables/variable-types/global-variables/

**Comment by manjunathnayaka22** [comment]
I referred the above link also follow the below step, but still not getting the data it shows bad input. Following is the additional details, how to get last 2 min data by adding the input variable in this url?
Here is the url: https://phx-ipc1-eom1-mgmt.phx.aexp.com/me/r/calls/
my input name is : Interval


Using Grafana's time filter
Once you setup the query, you may find that your are always querying recent data in the graphs irrespective of the time range chosen in Grafana. To solve this issue, we need to pass the Grafana's dynamic time range in the url. As per the [ThingSpeak API specification](https://community.thingspeak.com/documentation%20.../api/), you need to pass the start and end time to the url as query string params. To do that, I am appending ?start=${__from:date:YYYY-MM-DD HH:NN:SS}&end=${__to:date:YYYY-MM-DD HH:NN:SS} to the url. You can use any variable as specified in the [grafana doc](https://grafana.com/docs/grafana/latest/variables/variable-types/global-variables/)

My full url now becomes https://thingspeak.com/channels/38629/feed.json?start=${__from:date:YYYY-MM-DD HH:NN:SS}&end=${__to:date:YYYY-MM-DD HH:NN:SS}.

**Comment by yesoreyeram** [comment]
Hi Manju. Sorry to spoon feed. Looks like you need `https://test.com/me/r/calls/${__from:date:YYYY-MM-HH}+${__from:date:hh}:${__from:date:mm}:${__from:date:ss}/${__to:date:YYYY-MM-HH}+${__to:date:hh}:${__to:date:mm}:${__to:date:ss}` as your URL

https://grafana.com/docs/grafana/latest/variables/variable-types/global-variables/#__from-and-__to

<img width="1790" alt="image" src="https://user-images.githubusercontent.com/153843/171035322-a8532644-3b77-4c75-b137-d8f2edd0ad34.png">
<img width="1106" alt="image" src="https://user-images.githubusercontent.com/153843/171035358-3073c839-f1ff-41f0-92ec-c13864a1efb4.png">
